version: '3.7'
services:
db:
  image:mysql: 5.7
  restart: always
ports:
   -"3306:3306"
environment:
   MYSQL_DATABASE: 'mobile_ref_data_items'
   MYSQL_ALLOW_EMPTY_PASSWORD: 1
   MYSQL_PASSWORD: ""
app:
  build:
    context: .
    dockerfile: .docker/Dockerfile
  image: 'mobile_laravel'
  ports:
    -"8080:80"
  volumes:
     - ./:/var/www/html

